# Generated by Django 5.2.1 on 2025-05-29 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_life', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acquisto',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='casaproduzione',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='gioco',
            options={'ordering': ['-data_uscita']},
        ),
        migrations.AlterModelOptions(
            name='recensione',
            options={'ordering': ['-data_pubblicazione']},
        ),
        migrations.AlterModelOptions(
            name='venditore',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='acquisto',
            name='metodo_pagamento',
            field=models.CharField(choices=[('Carta', 'Carta di credito'), ('PayPal', 'PayPal'), ('Bonifico', 'Bonifico bancario')], default='Carta', help_text='Metodo utilizzato per il pagamento', max_length=20),
        ),
        migrations.AddField(
            model_name='casaproduzione',
            name='anno_fondazione',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='casaproduzione',
            name='sede',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_registrazione',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='cliente@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='gioco',
            name='data_uscita',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='gioco',
            name='descrizione',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gioco',
            name='genere',
            field=models.CharField(default='Azione', help_text='Es: Azione, Avventura, Puzzle', max_length=50),
        ),
        migrations.AddField(
            model_name='gioco',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, default=59.99, max_digits=6),
        ),
        migrations.AddField(
            model_name='recensione',
            name='data_pubblicazione',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='recensione',
            name='voto',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='venditore',
            name='contatto_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='venditore',
            name='sito_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acquisto',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='casaproduzione',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gioco',
            name='titolo',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='venditore',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
